name: Create and publish a Docker image

on:
  push:
    tags:
      - "v*"


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{  github.ref_name }}
  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-image:
    name: Build image and update Helm Chart values
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clone Helm chart repo and update new containter image tags
        run: |
          echo New container image tag: ${{ env.IMAGE_TAG }}
          echo Create temp directory to clone helm repo
          TEMP_DIR=="$(mktemp -d)"
          echo Clone the repository...
          git clone -b main "https://origox:${ACCESS_TOKEN}@github.com/origox/k3s-microservice-ci-cd-helm-charts.git" ${TEMP_FOLDER} 
          cd ${TEMP_DIR}/application-charts/fastapi 
          ls
          CONTAINER_IMAGE_TAG=$CONTAINER_IMAGE_TAG yq e -i '.fastapi.deployment.imageTag = env(CONTAINER_IMAGE_TAG)' ./values.yaml
          echo 'Container image tag updated in fastapi/values.yaml' 
          cd ../../
          git config user.email "jfrandberg@gmail.com" 
          git config user.name "origox" 
          git add .  
          git commit -m "refactor - updated Helm chart values for environment with container image - $CONTAINER_IMAGE_TAG" 
          git push -u origin main